---
title: "jae_work"
output: html_document
date: "2025-03-27"
---

```{r}
# load libraries
library(tidyverse)
library(ggplot2)
library(forecast)
library(lubridate)
library(dplyr)
library(astsa)
library(fGarch)
library(xts)
library(rugarch)
```

```{r} 
# load data
prices_data <- read_csv("DailyPrices_ICCO.csv", show_col_types=TRUE)
ghana_data <- read_csv("Ghana_data.csv", show_col_types=TRUE)
```

```{r}
clean_ghana <- ghana_data %>%
  mutate(DATE = ymd(DATE)) %>%
  distinct(DATE, .keep_all = TRUE) %>%
  filter(between(DATE, ymd("1994-10-03"), ymd("2024-11-28")))
```

```{r}
total_duplicates <- sum(duplicated(clean_ghana))
final_ghana <- clean_ghana %>%
  select(DATE, PRCP, TAVG)
```


```{r}
# Find rows with duplicated dates
duplicate_dates <- prices_data %>%
  group_by(Date) %>%        # Group by the "Date" column
  filter(n() > 1) %>%       # Keep dates that appear more than once
  arrange(Date) %>%         # Sort by date for clarity
  ungroup()

# Modify the column name from ICCO daily price (US$/tonne) to Price
prices_data <- rename(
  prices_data, 
  Price=`ICCO daily price (US$/tonne)`
)

# View the results
print(duplicate_dates)

```


```{r}
data <- prices_data %>%
  mutate(Date = ymd(Date)) %>%
  arrange(Date) %>%
  mutate(
    next_price = lead(Price),
    next_date = lead(Date),
    days_diff = as.numeric(next_date - Date),
    price_diff = next_price - Price
  ) %>%
  filter(
    days_diff == 1,          # Strictly consecutive days
    price_diff > 100,        # Price increase > $100
    !is.na(price_diff)       # Remove NA from the last row
  ) %>%
  select(Date, Price, next_date, next_price, price_diff)
```

```{r}
clean_price <- prices_data %>%
  distinct() %>%
  filter(!(Date == "30/01/2024" & `Price` == 10676.42)) %>%
  filter(!(Date == "31/01/2024" & `Price` == 10888.05))
```

```{r}
# Find rows with duplicated dates
duplicate_dates <- clean_price %>%
  group_by(Date) %>%        # Group by the "Date" column
  filter(n() > 1) %>%       # Keep dates that appear more than once
  arrange(Date) %>%         # Sort by date for clarity
  ungroup()

print(duplicate_dates)

```


```{r}
final_price <- clean_price %>%
  select(Date, `Price`)
```


```{r}
final_price <- final_price %>%
  mutate(Date = as.Date(Date, format = "%d/%m/%Y"))
# Ensure DATE column is already Date type (if not, convert)
final_ghana <- final_ghana %>%
  mutate(DATE = as.Date(DATE))

```



```{r}
combined_data <- final_price %>%
  inner_join(final_ghana, by = c("Date" = "DATE"))

combined_data
```


```{r}
sorted_data <- combined_data %>%
  mutate(Date = ymd(Date)) %>%       # Convert to proper date format
  arrange(Date) %>%                 # Sort by ascending date
  select(Date, everything())        # Ensure date column comes first

# View sorted data
sorted_data
```
```{r}
sorted_data <- sorted_data %>%
  rename(
    date = Date,
    daily_price = `Price`,  
    precipitation = PRCP,                               
    avg_temperature = TAVG                             
  )

```

```{r}
# only keep date and daily_price
univariate_data <- sorted_data %>%
  select(date, daily_price)
head(univariate_data)

# from univariate data, check if there are misisng dates
missing_dates <- univariate_data %>%
  complete(date = seq.Date(min(date), max(date), by = "day")) %>%
  filter(is.na(daily_price))

length(missing_dates$date)
```

```{r}
# take the monthly average
monthly_avg <- univariate_data %>%
  mutate(year_month = format(date, "%Y-%m")) %>%
  group_by(year_month) %>%
  summarise(avg_price = mean(daily_price, na.rm = TRUE))

monthly_avg$year_month <- ym(monthly_avg$year_month)


# make monthly_avg date type
# check if there are missing months
missing_months <- monthly_avg %>%
  complete(year_month = seq.Date(min(year_month), max(year_month), by = "month")) %>%
  filter(is.na(avg_price))

# use linear interpolation to fill in missing values
monthly_avg <- monthly_avg %>%
  complete(year_month = seq.Date(min(year_month), max(year_month), by = "month")) %>%
  fill(avg_price) %>%
  arrange(year_month)

monthly_avg
```
```{r}
# keep train data as dates 2023 and before
train_data <- monthly_avg %>%
  filter(year_month < ym("2024-01"))

test_data <- monthly_avg %>%
  filter(year_month >= ym("2023-12"))
```


```{r}
univariate_ts <- ts(train_data$avg_price, frequency = 12, start = c(1994, 10))
```

```{r}
univariate_ts
```


```{r}
# check ACF and PACF
xt = diff(log(univariate_ts))
# xt = log(yt) - log(yt-1)
plot(xt)
```

```{r}
acf2(xt)

model_AR1 = sarima(xt, 1, 0, 0)
model_MA1 = sarima(xt, 0, 0, 1)
sresxt = resid(model_AR1$fit)

res_sq = sresxt^2 #Squared residuals
acf2(res_sq, max.lag = 50) #It shows that there are some dependencies among residuals
```

```{r}
garch_model_10 = garchFit(~arma(0,1)+garch(1,0), xt, cond.dist='std')
garch_model_11 = garchFit(~arma(0,1)+garch(1,1), xt, cond.dist='std')
garch_model_20 = garchFit(~arma(0,1)+garch(2,0), xt, cond.dist='std')
garch_model_12 = garchFit(~arma(0,1)+garch(1,2), xt, cond.dist='std')
```


```{r}
# Forecasting
# compare with test data
test_ts <- ts(test_data$avg_price, frequency = 12, start = c(2023, 12))
garch_model_10_forecast <- predict(garch_model_10, n.ahead = 11)
garch_model_11_forecast <- predict(garch_model_11, n.ahead = 11)
garch_model_20_forecast <- predict(garch_model_20, n.ahead = 11)
garch_model_12_forecast <- predict(garch_model_12, n.ahead = 11)
test_price <- diff(log(test_ts))
test_price <- test_price[1:11]
```

```{r}
#make a dataframe for the forecasted values
forecasted_values <- data.frame(
  garch_model_10_forecast$meanForecast,
  garch_model_11_forecast$meanForecast,
  garch_model_20_forecast$meanForecast,
  garch_model_12_forecast$meanForecast,
  test_price
)
# find mape for each model
mape_garch_10 <- sum(abs((forecasted_values$garch_model_10_forecast - forecasted_values$test_price)/forecasted_values$test_price))/11
mape_garch_11 <- sum(abs((forecasted_values$garch_model_11_forecast - forecasted_values$test_price)/forecasted_values$test_price))/11
mape_garch_20 <- sum(abs((forecasted_values$garch_model_20_forecast - forecasted_values$test_price)/forecasted_values$test_price))/11
mape_garch_12 <- sum(abs((forecasted_values$garch_model_12_forecast - forecasted_values$test_price)/forecasted_values$test_price))/11

#print each mape
print(mape_garch_10)
print(mape_garch_11)
print(mape_garch_20)
print(mape_garch_12)
```


```{r}
# now revert back to the original scale
# xt = diff(log(univariate_ts))
# xt = log(yt) - log(yt-1)
# log(yt) = xt + log(yt-1)
# yt = exp(xt + log(yt-1))

forecased_price_scaled_10 = exp(forecasted_values$garch_model_10_forecast + log(test_ts[1]))
forecased_price_scaled_11 = exp(forecasted_values$garch_model_11_forecast + log(test_ts[1]))
forecased_price_scaled_20 = exp(forecasted_values$garch_model_20_forecast + log(test_ts[1]))
forecased_price_scaled_12 = exp(forecasted_values$garch_model_12_forecast + log(test_ts[1]))

length(test_ts[1:11])
# make a dataframe for the forecasted values
forecasted_values_scaled <- data.frame(
  forecased_price_scaled_10,
  forecased_price_scaled_11,
  forecased_price_scaled_20,
  forecased_price_scaled_12,
  test_ts[1:11]
)

# find mape for each model
mape_garch_10_scaled <- sum(abs((forecasted_values_scaled$forecased_price_scaled_10 - forecasted_values_scaled$test_ts)/forecasted_values_scaled$test_ts))/11
mape_garch_11_scaled <- sum(abs((forecasted_values_scaled$forecased_price_scaled_11 - forecasted_values_scaled$test_ts)/forecasted_values_scaled$test_ts))/11
mape_garch_20_scaled <- sum(abs((forecasted_values_scaled$forecased_price_scaled_20 - forecasted_values_scaled$test_ts)/forecasted_values_scaled$test_ts))/11
mape_garch_12_scaled <- sum(abs((forecasted_values_scaled$forecased_price_scaled_12 - forecasted_values_scaled$test_ts)/forecasted_values_scaled$test_ts))/11

#print each mape
print(mape_garch_10_scaled)
print(mape_garch_11_scaled)
print(mape_garch_20_scaled)
print(mape_garch_12_scaled)

```








